### ISSUE TITLE
Polly support

### ISSUE THREAD

**Issue by eduherminio** [weblinq/WebLinq#140]
It would be great to have some support for [Polly](https://github.com/App-vNext/Polly) in IHttpClient.
Is there anything similar already built-in, or is it something that could be considered for the future?

**Comment by atifaziz** [comment]
There is nothing already built-into WebLINQ although you can use things like [`Observable.Retry`](http://reactivex.io/documentation/operators/retry.html) and other similar extensions from Rx to get some of the same benefits.

I don't think there'll be anything added in the future (speaking for myself) unless it comes from a contributor who has experience with Polly and created a field/battle-tested implementation that integrates it with `IHttpClient`. Part of the reason for having `IHttpClient` is precisely so everything doesn't have to be built-into WebLINQ and people can build extensions.
