### ISSUE TITLE
Executing a query in a script hangs the interactive

### ISSUE THREAD

**Issue by gmpl** [weblinq/WebLinq#15]
REPRO STEPS:

Reference ths DLLs with #r, open the namespaces and paste the following code in a C# script interactive:

```c#
static void GetNasdaqPrices(string symbol)
{
    // Historical Prices Site (NASDAQ)
    string url = $"http://www.nasdaq.com/symbol/{symbol}/historical";

    var data =
        from html in Http.Get(new Uri(url)).Html().Content()
        from table in html.Tables("#historicalContainer table")
        from row in table.QuerySelectorAll("tr")
        let cells = row.QuerySelectorAll("td").Select(td => td.InnerText).ToArray()
        where cells.Length == 6
        select new
        {
            Date   = cells[0].Trim(),
            Open   = cells[1].Trim(),
            High   = cells[2].Trim(),
            Low    = cells[3].Trim(),
            Close  = cells[4].Trim(),
            Volume = cells[5].Trim(),
        }
        into row
        where row.Date.Length > 0 // skip invalid rows
        select row;
    data.Dump();
}
static void Dump<T>(this IQuery<T> query, TextWriter output = null)
{
    output = output ?? Console.Out;
    foreach (var e in query.ToEnumerable(DefaultQueryContext.Create))
        output.WriteLine(e);
}
GetNasdaqPrices("v")
```

By sniffing the network it seems the query succeeds but the interactive hangs and it never comes back.

NOTE: The same behavior is observed in F# Interactive with the corresponding F# translation of the Query.

**Comment by atifaziz** [comment]
@gmpl I just tried the following in a C# interactive console and it worked perfectly fine:

```
Microsoft (R) Visual C# Interactive Compiler version 1.3.1.60616
Copyright (C) Microsoft Corporation. All rights reserved.

Type "#help" for more information.
> #r "A:\WebLinq\bin\Debug\WebLinq.dll"
> using WebLinq;
> using WebLinq.Html;
> using static WebLinq.HttpQuery;
> var symbol = "v";
> var url = $"http://www.nasdaq.com/symbol/{symbol}/historical";
> var data =
.     from html in Http.Get(new Uri(url)).Html().Content()
.     from table in html.Tables("#historicalContainer table")
.     from row in table.QuerySelectorAll("tr")
.     let cells = row.QuerySelectorAll("td").Select(td => td.InnerText).ToArray()
.     where cells.Length == 6
.     select new
.     {
.     Date   = cells[0].Trim(),
.     Open   = cells[1].Trim(),
.     High   = cells[2].Trim(),
.     Low    = cells[3].Trim(),
.     Close  = cells[4].Trim(),
.     Volume = cells[5].Trim(),
.     }
.     into row
.     where row.Date.Length > 0 // skip invalid rows
.     select row;
> foreach (var e in data.ToEnumerable(DefaultQueryContext.Create).Take(10))
.     Console.WriteLine(e);
{ Date = 16:00, Open = 81.12, High = 81.78, Low = 80.90, Close = 81.69, Volume = 8,942,057 }
{ Date = 11/21/2016, Open = 81.23, High = 81.78, Low = 80.9, Close = 81.69, Volume = 8,857,014 }
{ Date = 11/18/2016, Open = 81.15, High = 81.5, Low = 80.53, Close = 80.82, Volume = 7,908,997 }
{ Date = 11/17/2016, Open = 80.32, High = 81.2, Low = 80.18, Close = 81.07, Volume = 7,888,706 }
{ Date = 11/16/2016, Open = 78.79, High = 80.19, Low = 78.76, Close = 80.08, Volume = 9,940,845 }
{ Date = 11/15/2016, Open = 78.23, High = 79.54, Low = 77.795, Close = 78.57, Volume = 18,513,640 }
{ Date = 11/14/2016, Open = 82.02, High = 82.22, Low = 77.3, Close = 78.38, Volume = 21,710,300 }
{ Date = 11/11/2016, Open = 81.59, High = 82.63, Low = 81.52, Close = 81.88, Volume = 7,356,319 }
{ Date = 11/10/2016, Open = 83.3, High = 83.96, Low = 81.415, Close = 81.87, Volume = 17,064,990 }
{ Date = 11/09/2016, Open = 81.81, High = 83.3, Low = 81.22, Close = 83.24, Volume = 12,130,910 }
>
```

This was test on 0ba094cd43281c24680f495c4e36d407802cb91d from `master`.

**Comment by atifaziz** [comment]
Also pasted the code you quoted (had moved and define `Dump` before `GetNasdaqPrices`) and it worked just fine. No hanging.

**Comment by gmpl** [comment]
Your code doesn't work in my machine at work (Windows with Visual Studio 2015).
And I didn't try it at home, but the F# script fails in my home computer (Mac emulating Windows with VS2015).

I know, having said that it looks like the problem is between the keyboard and the chair but still trying to figure it out ;)

**Comment by atifaziz** [comment]
What version of `csi.exe` are you running. I quoted mine in the interactive session dump above as 1.3.1.60616. Could be a bug from an older version?

**Comment by gmpl** [comment]
On the contrary your version is older than mine:

    Microsoft (R) Roslyn C# Compiler version 1.3.3.60707
    Loading context from 'CSharpInteractive.rsp'.

I don't think is specific to C# or F# interactive. Can you try the F# version? To discard a specific problem with C# Interactive.

**Comment by gmpl** [comment]
Here's a smaller repro:

    #r "C:\repos\WebLinq\src\Core\..\..\bin\Debug\WebLinq.dll"
    using WebLinq;
    using WebLinq.Html;
    using static WebLinq.HttpQuery;

    var data = from link in Http.Get(new Uri("http://www.google.com")).Links()
        select link.Content;

    foreach (var e in data.ToEnumerable(DefaultQueryContext.Create).Take(10))
        Console.WriteLine(e);

As soon as I press ENTER I get the circle in the mouse pointer.

**Comment by atifaziz** [comment]
What version are you on?

**Comment by gmpl** [comment]
I'm on the latest from master at https://github.com/weblinq/WebLinq/commit/0ba094cd43281c24680f495c4e36d407802cb91d 
Same as you.

**Comment by atifaziz** [comment]
Sorry, I meant the C# Interactive version but now I see that you quoted your version. Have you already applied “[Cumulative Servicing Release for Microsoft Visual Studio 2015 Update 3 (KB3165756)](https://msdn.microsoft.com/en-us/library/mt752379.aspx)”? I haven't so perhaps there's a new version shipping in there that has the issue?

**Comment by gmpl** [comment]
Yes, it seems it is already applied:

Microsoft Visual Studio Professional 2015
Version 14.0.25425.01 **Update 3**
Microsoft .NET Framework
Version 4.6.01055

Installed Version: Professional

LightSwitch for Visual Studio 2015   00322-40000-00000-AA964
Microsoft LightSwitch for Visual Studio 2015

Visual Basic 2015   00322-40000-00000-AA964
Microsoft Visual Basic 2015

Visual C# 2015   00322-40000-00000-AA964
Microsoft Visual C# 2015

Visual C++ 2015   00322-40000-00000-AA964
Microsoft Visual C++ 2015

Visual F# 2015   00322-40000-00000-AA964
Microsoft Visual F# 2015

Application Insights Tools for Visual Studio Package   7.12.01117.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2015.1 (Beta8)   14.1.11107.0
ASP.NET and Web Tools 2015.1 (Beta8)

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
For additional information, visit http://www.asp.net/

Bundler & Minifier   1.0.21
Adds support for bundling and minifying JavaScript, CSS and HTML files in any project.

Code alignment   13.1
Code alignment helps you present your code beautifully, enhancing clarity and readability.

Common Azure Tools   1.8
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JetBrains ReSharper Ultimate 2016.1.2    Build 105.0.20160522.80219
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2016 JetBrains, Inc.

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

NuGet Package Manager   3.4.4
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Office Developer Tools for Visual Studio 2015 ENU   14.0.23025
Microsoft Office Developer Tools for Visual Studio 2015 ENU

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

SQL Server Data Tools   14.0.60519.0
Microsoft SQL Server Data Tools

TypeScript   1.8.36.0
TypeScript tools for Visual Studio

Workflow Manager Tools 1.0   1.0
This package contains the necessary Visual Studio integration components for Workflow Manager.

**Comment by atifaziz** [comment]
Version 14.0.25425.01 Update 3 is not the latest. It's from [August 2nd, 2016](https://msdn.microsoft.com/en-us/library/mt752379.aspx#Anchor_3). Nevertheless, it's still a couple of patches ahead of mine, which is form [June 27, 2016](https://msdn.microsoft.com/en-us/library/mt752379.aspx#Anchor_6).

**Comment by atifaziz** [comment]
I updated to the latest version (14.0.25431.01 Update 3) and my `csi.exe` version has remained the same so that's not it.
